const API='https://nexa-backend-p2u0.onrender.com/api/v1';
let tab='ops',data={};
const $=id=>document.getElementById(id);
const token=()=>sessionStorage.getItem('nexa_admin_token')||'';
const setToken=t=>t?sessionStorage.setItem('nexa_admin_token',t):sessionStorage.removeItem('nexa_admin_token');
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const n=(v,d=2)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pill=(v,t='')=>'<span class="pill '+t+'">'+esc(v||'-')+'</span>';
const statusClass=s=>s==='completed'?'green':s==='failed'?'red':'yellow';
async function call(path,opt={}){if(!token())throw new Error('Sessão administrativa não iniciada');const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token(),...(opt.headers||{})}});const txt=await r.text();let j;try{j=txt?JSON.parse(txt):{}}catch{j={raw:txt}}if(r.status===401||r.status===403){logout(false);throw new Error('Sessão expirada ou acesso não autorizado')}if(!r.ok)throw new Error(j.message||j.error||txt||('HTTP '+r.status));return j}
async function login(){try{const email=$('email').value.trim(),password=$('password').value;if(!email||!password){alert('Informe e-mail e senha');return}$('status').textContent='Entrando...';const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const txt=await r.text();let j;try{j=JSON.parse(txt)}catch{j={raw:txt}}const accessToken=j.accessToken||j.access_token||j.token;if(!r.ok||!accessToken)throw new Error(j.message||j.error||txt||'Login falhou');setToken(accessToken);$('password').value='';await refresh()}catch(e){setToken('');data={};$('status').textContent='Erro: '+e.message;render();alert(e.message)}}
function logout(show=true){setToken('');data={};$('status').textContent='Sessão encerrada';render();if(show)alert('Sessão encerrada.')}
async function refresh(){if(!token()){render();return}try{$('status').textContent='Carregando painel...';const [ops,users,treasury,clientsFull,dash,deposits]=await Promise.all([call('/admin/ops-center'),call('/admin/users'),call('/treasury-admin/dashboard'),call('/treasury-admin/clients-full'),call('/admin/dashboard'),call('/admin/deposits')]);data={ops:ops||{},users:users||[],treasury:treasury||{},clientsFull:clientsFull||{},dash:dash||{},deposits:deposits||[],ledgerBalances:{}};await Promise.all(clients().map(async c=>{try{const b=await call('/ledger/balance?userId='+encodeURIComponent(c.id)+'&mode=real');data.ledgerBalances[c.id]=b.balances||{}}catch{data.ledgerBalances[c.id]={}}}));$('status').textContent='Painel carregado';render()}catch(e){$('status').textContent='Erro: '+e.message;render()}}
function clients(){return data.clientsFull?.clients||data.users||[]}
function clientById(id){return clients().find(c=>c.id===id)||{}}
function ledgerUsdc(c){return Number(data.ledgerBalances?.[c.id]?.USDC??c.balances?.USDC??c.availableBalanceUsdc??0)}
function payments(){return data.dash?.latest?.payments||[]}
function setTab(t){tab=t;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));render()}
function card(label,value,cls=''){return '<div class="card"><div class="muted">'+label+'</div><div class="kpi '+cls+'">'+value+'</div></div>'}
function fmtDate(v){if(!v)return'-';return new Date(v).toLocaleString('pt-BR')}
function deadlineDate(v){const d=new Date(v||Date.now());d.setDate(d.getDate()+1);return d}
function deadline(v){return deadlineDate(v).toLocaleString('pt-BR')}
function render(){$('title').textContent={ops:'Visão Geral',clientes:'Clientes',financeiro:'Saques Pix',tesouraria:'Tesouraria',crm:'CRM / SmartBots',conhecimento:'Conhecimento',raw:'Debug'}[tab]||tab;if(!token()){$('content').innerHTML='<div class="card"><h3>Acesso restrito</h3><p class="muted">Faça login para visualizar dados administrativos. Nenhuma informação é carregada antes da autenticação.</p></div>';return}if(tab==='ops')return renderOps();if(tab==='clientes')return renderClientes();if(tab==='financeiro')return renderFinanceiro();if(tab==='tesouraria')return renderTesouraria();if(tab==='crm')return renderCrm();$('content').innerHTML='<pre>'+esc(JSON.stringify(data,null,2))+'</pre>'}
function renderOps(){const open=payments().filter(p=>['pending','processing'].includes(String(p.status).toLowerCase()));const expired=open.filter(p=>deadlineDate(p.createdAt)<new Date());const total=open.reduce((s,p)=>s+Number(p.amountBrl||0),0);const oldest=open.slice().sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))[0];const o=data.ops||{},t=data.treasury||{};$('content').innerHTML='<div class="grid">'+card('Saques aguardando',open.length,open.length?'warn':'ok')+card('Valor total',brl(total))+card('Prazo vencido',expired.length,expired.length?'bad':'ok')+card('Mais antigo',oldest?fmtDate(oldest.createdAt):'Nenhum')+'</div><div class="card notice"><h3>Operação Manual Blindada v1.0</h3><p>O cliente solicita online, o USDC é reservado imediatamente e o pedido chega por e-mail. Faça o Pix manualmente e encerre o pedido no painel. Pix Out automático permanece desligado.</p><button onclick="setTab(\'financeiro\')">Abrir fila de saques</button></div><div class="grid">'+card('Status do sistema',esc(o.health?.status||'ok'),'ok')+card('Clientes',clients().length)+card('USDC clientes',n(t.liabilities?.clientUsdcLiability,8))+card('Modelo Pix Out','MANUAL','ok')+'</div>'}
function renderClientes(){const rows=clients();$('content').innerHTML='<div class="grid">'+card('Total',rows.length)+card('KYC aprovado',rows.filter(x=>x.kycStatus==='approved').length,'ok')+card('Com saldo',rows.filter(x=>ledgerUsdc(x)>0).length)+card('Bloqueados',rows.filter(x=>x.isBlocked||x.isActive===false).length,'warn')+'</div><div class="card notice"><b>Saldo oficial:</b> Ledger. O campo técnico de cache não é exibido.</div><div class="card scroll"><table><thead><tr><th>Nome</th><th>Contato</th><th>KYC</th><th>Saldo oficial</th><th>Ações</th></tr></thead><tbody>'+rows.map(u=>'<tr><td><b>'+esc(u.fullName||'-')+'</b><br><span class="muted">'+esc(u.cpfCnpj||u.cpf||'-')+' @'+esc(u.username||'-')+'</span></td><td>'+esc(u.email||'-')+'<br>'+esc(u.phone||'-')+'</td><td>'+pill(u.kycStatus,u.kycStatus==='approved'?'green':'yellow')+'</td><td><b>'+n(ledgerUsdc(u),8)+' USDC</b><br><span class="muted">'+brl(data.ledgerBalances?.[u.id]?.BRL||0)+'</span></td><td><button class="green" onclick="openClientCrm(\''+u.id+'\')">CRM</button><button onclick="report(\''+u.id+'\')">Relatório</button></td></tr>').join('')+'</tbody></table></div>'}
function renderFinanceiro(){const ps=payments().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const open=ps.filter(p=>['pending','processing'].includes(String(p.status).toLowerCase()));const expired=open.filter(p=>deadlineDate(p.createdAt)<new Date());const total=open.reduce((s,p)=>s+Number(p.amountBrl||0),0);const oldest=open.slice().sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))[0];const openCards=open.map(p=>{const c=clientById(p.userId),late=deadlineDate(p.createdAt)<new Date();return '<div class="card '+(late?'critical':'')+'"><div class="eyebrow">'+(late?'PRAZO VENCIDO':'SAQUE AGUARDANDO')+'</div><h2>Faça o Pix de '+brl(p.amountBrl)+'</h2><p><b>Cliente:</b> '+esc(c.fullName||p.userId)+'<br><b>E-mail:</b> '+esc(c.email||'-')+'<br><b>Chave Pix:</b> '+esc(p.pixKey||'-')+'<br><b>USDC reservado:</b> '+n(p.amountUsdc,8)+'<br><b>Solicitado:</b> '+fmtDate(p.createdAt)+'<br><b>Prazo:</b> '+deadline(p.createdAt)+'</p><div class="actions"><button class="green" onclick="finishPayment(\''+p.id+'\',\'completed\')">PIX REALIZADO</button><button class="red" onclick="finishPayment(\''+p.id+'\',\'failed\')">RECUSAR E DEVOLVER USDC</button></div><p class="muted">Pedido #'+esc(p.id)+'</p></div>'}).join('');const history=ps.filter(p=>!['pending','processing'].includes(String(p.status).toLowerCase())).map(p=>{const c=clientById(p.userId),s=String(p.status||'').toLowerCase();return '<tr><td>'+fmtDate(p.createdAt)+'</td><td>'+esc(c.fullName||p.userId)+'</td><td>'+brl(p.amountBrl)+'</td><td>'+pill(s,statusClass(s))+'</td><td>'+esc(p.failureReason||'-')+'</td></tr>'}).join('');$('content').innerHTML='<div class="grid">'+card('Saques aguardando',open.length,open.length?'warn':'ok')+card('Valor total',brl(total))+card('Vencidos',expired.length,expired.length?'bad':'ok')+card('Mais antigo',oldest?fmtDate(oldest.createdAt):'Nenhum')+'</div><div class="card notice"><b>Procedimento:</b> confira cliente, valor e chave; faça o Pix; só então clique em PIX REALIZADO. Se não pagar, use RECUSAR E DEVOLVER USDC. Nunca altere o saldo manualmente.</div><div class="grid2">'+(openCards||'<div class="card goodbox"><h3>Nenhum saque aguardando.</h3></div>')+'</div><h3>Histórico encerrado</h3><div class="card scroll"><table><thead><tr><th>Data</th><th>Cliente</th><th>Valor</th><th>Status</th><th>Observação</th></tr></thead><tbody>'+history+'</tbody></table></div>'}
function renderTesouraria(){const t=data.treasury||{},r=t.reserves||{},l=t.liabilities||{};$('content').innerHTML='<div class="grid">'+card('Treasury USDC',n(r.treasuryUsdc,8),'ok')+card('USDC clientes',n(l.clientUsdcLiability,8))+card('Gap',n(r.reserveGapUsdc,8),Number(r.reserveGapUsdc)>=0?'ok':'bad')+card('Fila de compra',n(t.purchaseQueue?.usdcToBuy,8))+'</div><div class="card"><p>O USDC do saque é reservado no pedido. Marcar como pago não debita novamente. Recusar devolve exatamente a reserva uma única vez.</p></div>'}
function renderCrm(){$('content').innerHTML='<div class="card"><h3>Clientes</h3><p class="muted">Use o botão CRM na lista de clientes para abrir contato e acompanhamento.</p></div>'}
function openClientCrm(id){const c=clientById(id);const phone=String(c.phone||'').replace(/\D/g,'');const msg='Olá, '+String(c.fullName||'cliente').split(' ')[0]+'! Aqui é a Nexa. Como podemos ajudar?';if(phone)window.open('https://wa.me/55'+phone.replace(/^55/,'')+'?text='+encodeURIComponent(msg),'_blank');else alert('Cliente sem telefone cadastrado.')}
async function report(id){alert(JSON.stringify(await call('/admin/clients/'+id+'/report'),null,2).slice(0,5000))}
async function finishPayment(id,status){let reason='';if(status==='completed'){if(!confirm('Confirma que o Pix foi REALMENTE enviado? O saldo já foi debitado no pedido e não será debitado novamente.'))return}else{reason=prompt('Motivo da recusa (obrigatório):','Dados Pix inválidos ou pagamento não realizado')||'';if(!reason.trim()){alert('Informe o motivo da recusa.');return}if(!confirm('Confirma que este Pix NÃO foi enviado e que o USDC reservado deve voltar ao cliente?'))return}try{await call('/payment/confirm',{method:'POST',body:JSON.stringify({paymentId:id,status,reason:reason.trim()})});alert(status==='completed'?'Saque concluído.':'Saque recusado e USDC devolvido.');await refresh()}catch(e){alert('Erro: '+e.message)}}
document.addEventListener('DOMContentLoaded',()=>{setToken('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('loginBtn').onclick=login;$('logoutBtn').onclick=()=>logout(true);$('refreshBtn').onclick=refresh;$('password').onkeydown=e=>{if(e.key==='Enter')login()};setTab('ops');render()});