const API='https://nexa-backend-p2u0.onrender.com/api/v1';
let tab='ops',data={};
const $=id=>document.getElementById(id);
const token=()=>sessionStorage.getItem('nexa_admin_token')||'';
const setToken=t=>t?sessionStorage.setItem('nexa_admin_token',t):sessionStorage.removeItem('nexa_admin_token');
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const n=(v,d=2)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pill=(v,t='')=>'<span class="pill '+t+'">'+esc(v||'-')+'</span>';
const statusClass=s=>s==='completed'?'green':s==='failed'?'red':'yellow';
async function call(path,opt={}){if(!token())throw new Error('Sessão administrativa não iniciada');const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token(),...(opt.headers||{})}});const txt=await r.text();let j;try{j=txt?JSON.parse(txt):{}}catch{j={raw:txt}}if(r.status===401||r.status===403){logout(false);throw new Error('Sessão expirada ou acesso não autorizado')}if(!r.ok)throw new Error(j.message||j.error||txt||('HTTP '+r.status));return j}
async function login(){try{const email=$('email').value.trim(),password=$('password').value;if(!email||!password){alert('Informe e-mail e senha');return}$('status').textContent='Entrando...';const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const txt=await r.text();let j;try{j=JSON.parse(txt)}catch{j={raw:txt}}const accessToken=j.accessToken||j.access_token||j.token;if(!r.ok||!accessToken)throw new Error(j.message||j.error||txt||'Login falhou');setToken(accessToken);$('password').value='';await refresh()}catch(e){setToken('');data={};$('status').textContent='Erro: '+e.message;render();alert(e.message)}}
function logout(show=true){setToken('');data={};$('status').textContent='Sessão encerrada';render();if(show)alert('Sessão encerrada.')}
async function refresh(){if(!token()){render();return}try{$('status').textContent='Carregando painel...';const [ops,users,treasury,clientsFull,dash,deposits]=await Promise.all([call('/admin/ops-center'),call('/admin/users'),call('/treasury-admin/dashboard'),call('/treasury-admin/clients-full'),call('/admin/dashboard'),call('/admin/deposits')]);data={ops:ops||{},users:users||[],treasury:treasury||{},clientsFull:clientsFull||{},dash:dash||{},deposits:deposits||[],ledgerBalances:{}};await Promise.all(clients().map(async c=>{try{const b=await call('/ledger/balance?userId='+encodeURIComponent(c.id)+'&mode=real');data.ledgerBalances[c.id]=b.balances||{}}catch{data.ledgerBalances[c.id]={}}}));$('status').textContent='Painel carregado';render()}catch(e){$('status').textContent='Erro: '+e.message;render()}}
function clients(){return data.clientsFull?.clients||data.users||[]}
function clientById(id){return clients().find(c=>c.id===id)||{}}
function ledgerUsdc(c){return Number(data.ledgerBalances?.[c.id]?.USDC??c.balances?.USDC??c.availableBalanceUsdc??0)}
function payments(){return data.dash?.latest?.payments||[]}
function setTab(t){tab=t;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));render()}
function card(label,value,cls=''){return '<div class="card"><div class="muted">'+label+'</div><div class="kpi '+cls+'">'+value+'</div></div>'}
function fmtDate(v){if(!v)return'-';return new Date(v).toLocaleString('pt-BR')}
function deadline(v){const d=new Date(v||Date.now());d.setDate(d.getDate()+1);return d.toLocaleString('pt-BR')}
function render(){$('title').textContent={ops:'Visão Geral',clientes:'Clientes',financeiro:'Financeiro / Pix',tesouraria:'Tesouraria',crm:'CRM / SmartBots',conhecimento:'Conhecimento',raw:'Debug'}[tab]||tab;if(!token()){$('content').innerHTML='<div class="card"><h3>Acesso restrito</h3><p class="muted">Faça login para visualizar dados administrativos. Nenhuma informação é carregada antes da autenticação.</p></div>';return}if(tab==='ops')return renderOps();if(tab==='clientes')return renderClientes();if(tab==='financeiro')return renderFinanceiro();if(tab==='tesouraria')return renderTesouraria();if(tab==='crm')return renderCrm();$('content').innerHTML='<pre>'+esc(JSON.stringify(data,null,2))+'</pre>'}
function renderOps(){const open=payments().filter(p=>['pending','processing'].includes(String(p.status).toLowerCase())).length;const o=data.ops||{},t=data.treasury||{};$('content').innerHTML='<div class="grid">'+card('Status',esc(o.health?.status||'ok'),'ok')+card('Clientes',clients().length)+card('Pedidos Pix abertos',open,open?'warn':'ok')+card('USDC clientes',n(t.liabilities?.clientUsdcLiability,8))+'</div><div class="card notice"><h3>Fluxo atual do saque Pix</h3><p>O pedido entra online, o saldo do cliente é reservado imediatamente e o cliente vê o valor reduzido. A Nexa informa prazo de até 1 dia útil. Até a automação Woovi ser validada, o pagamento é feito manualmente pelo administrador.</p><button onclick="setTab(\'financeiro\')">Abrir pedidos Pix</button></div>'}
function renderClientes(){const rows=clients();$('content').innerHTML='<div class="grid">'+card('Total',rows.length)+card('KYC aprovado',rows.filter(x=>x.kycStatus==='approved').length,'ok')+card('Com saldo',rows.filter(x=>ledgerUsdc(x)>0).length)+card('Bloqueados',rows.filter(x=>x.isBlocked||x.isActive===false).length,'warn')+'</div><div class="card notice"><b>Saldo exibido:</b> o painel e os produtos devem usar o Ledger oficial. A coluna técnica de cache foi removida para evitar confusão operacional.</div><div class="card scroll"><table><thead><tr><th>Nome</th><th>Contato</th><th>KYC</th><th>Saldo oficial</th><th>Ações</th></tr></thead><tbody>'+rows.map(u=>'<tr><td><b>'+esc(u.fullName||'-')+'</b><br><span class="muted">'+esc(u.cpfCnpj||u.cpf||'-')+' @'+esc(u.username||'-')+'</span></td><td>'+esc(u.email||'-')+'<br>'+esc(u.phone||'-')+'</td><td>'+pill(u.kycStatus,u.kycStatus==='approved'?'green':'yellow')+'</td><td><b>'+n(ledgerUsdc(u),8)+' USDC</b><br><span class="muted">'+brl(data.ledgerBalances?.[u.id]?.BRL||0)+'</span></td><td><button class="green" onclick="openClientCrm(\''+u.id+'\')">CRM</button><button onclick="report(\''+u.id+'\')">Relatório</button></td></tr>').join('')+'</tbody></table></div>'}
function renderFinanceiro(){const ps=payments().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const open=ps.filter(p=>['pending','processing'].includes(String(p.status).toLowerCase()));const completed=ps.filter(p=>p.status==='completed');$('content').innerHTML='<div class="grid">'+card('A fazer',open.length,open.length?'warn':'ok')+card('Valor pendente',brl(open.reduce((s,p)=>s+Number(p.amountBrl||0),0)))+card('Concluídos',completed.length,'ok')+card('Pix pagos',brl(completed.reduce((s,p)=>s+Number(p.amountBrl||0),0)))+'</div><div class="card notice"><h3>Procedimento simples</h3><p><b>1.</b> Faça o Pix exatamente para a chave indicada, até o prazo mostrado. <b>2.</b> Depois clique em “Marcar como pago”. <b>3.</b> Se não for possível pagar, clique em “Cancelar e devolver saldo”. O cliente recebe o USDC reservado de volta automaticamente.</p></div><div class="card scroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Instrução</th><th>USDC reservado</th><th>Status</th><th>Ações</th></tr></thead><tbody>'+ps.map(p=>{const c=clientById(p.userId),s=String(p.status||'').toLowerCase(),openRow=['pending','processing'].includes(s);return '<tr><td>'+fmtDate(p.createdAt)+'<br><span class="muted">#'+esc(p.id)+'</span></td><td><b>'+esc(c.fullName||p.userId)+'</b><br>'+esc(c.email||'')+'</td><td><b>Faça o Pix de '+brl(p.amountBrl)+'</b><br>Chave: <b>'+esc(p.pixKey||'-')+'</b><br>Até: <b>'+deadline(p.createdAt)+'</b></td><td>'+n(p.amountUsdc,8)+' USDC</td><td>'+pill(s,statusClass(s))+'<br><span class="muted">'+esc(p.failureReason||'')+'</span></td><td>'+(openRow?'<button class="green" onclick="finishPayment(\''+p.id+'\',\'completed\')">Marcar como pago</button><button class="red" onclick="finishPayment(\''+p.id+'\',\'failed\')">Cancelar e devolver saldo</button>':'Encerrado')+'</td></tr>'}).join('')+'</tbody></table></div>'}
function renderTesouraria(){const t=data.treasury||{},r=t.reserves||{},l=t.liabilities||{};$('content').innerHTML='<div class="grid">'+card('Treasury USDC',n(r.treasuryUsdc,8),'ok')+card('USDC clientes',n(l.clientUsdcLiability,8))+card('Gap',n(r.reserveGapUsdc,8),Number(r.reserveGapUsdc)>=0?'ok':'bad')+card('Fila de compra',n(t.purchaseQueue?.usdcToBuy,8))+'</div><div class="card"><p>O saldo reservado em pedidos Pix já sai do saldo disponível do cliente. Ao marcar como pago, não há segundo débito. Ao cancelar, a reserva é devolvida.</p></div>'}
function renderCrm(){$('content').innerHTML='<div class="card"><h3>Clientes</h3><p class="muted">Use o botão CRM na lista de clientes para abrir contato e acompanhamento.</p></div>'}
function openClientCrm(id){const c=clientById(id);const phone=String(c.phone||'').replace(/\D/g,'');const msg='Olá, '+String(c.fullName||'cliente').split(' ')[0]+'! Aqui é a Nexa. Como podemos ajudar?';if(phone)window.open('https://wa.me/55'+phone.replace(/^55/,'')+'?text='+encodeURIComponent(msg),'_blank');else alert('Cliente sem telefone cadastrado.')}
async function report(id){alert(JSON.stringify(await call('/admin/clients/'+id+'/report'),null,2).slice(0,5000))}
async function finishPayment(id,status){const text=status==='completed'?'Confirma que o Pix foi realmente enviado?':'Cancelar o pedido e devolver o USDC reservado ao cliente?';if(!confirm(text))return;try{await call('/payment/confirm',{method:'POST',body:JSON.stringify({paymentId:id,status})});alert(status==='completed'?'Pedido marcado como pago.':'Pedido cancelado e saldo devolvido.');await refresh()}catch(e){alert('Erro: '+e.message)}}
document.addEventListener('DOMContentLoaded',()=>{setToken('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('loginBtn').onclick=login;$('logoutBtn').onclick=()=>logout(true);$('refreshBtn').onclick=refresh;$('password').onkeydown=e=>{if(e.key==='Enter')login()};setTab('ops');render()});
