const API='https://nexa-backend-p2u0.onrender.com/api/v1';
let tab='ops',data={},leadFilter='',leadStatus='all';
const $=id=>document.getElementById(id);
const token=()=>sessionStorage.getItem('nexa_admin_token')||'';
const setToken=t=>t?sessionStorage.setItem('nexa_admin_token',t):sessionStorage.removeItem('nexa_admin_token');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:0,maximumFractionDigits:d});
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmtDate=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const pill=(v,t='')=>'<span class="pill '+t+'">'+esc(v||'—')+'</span>';
const statusClass=s=>String(s).toLowerCase()==='completed'?'green':['failed','cancelled','rejected'].includes(String(s).toLowerCase())?'red':'yellow';
const parseMoney=v=>{const s=String(v??'').trim().replace(/R\$/gi,'').replace(/\s/g,'');return Number(s.includes(',')?s.replace(/\./g,'').replace(',','.') : s)};

function toast(message,error=false){const el=$('toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3500)}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.add('open');$('modal').setAttribute('aria-hidden','false')}
function closeModal(){$('modal').classList.remove('open');$('modal').setAttribute('aria-hidden','true');$('modalContent').innerHTML=''}
function readableError(j,txt,status){const raw=j?.message||j?.error||j?.code||txt||('HTTP '+status);return Array.isArray(raw)?raw.join(', '):typeof raw==='object'?JSON.stringify(raw):String(raw)}
async function call(path,opt={}){if(!token())throw new Error('Sessão administrativa não iniciada');const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token(),...(opt.headers||{})}});const txt=await r.text();let j={};try{j=txt?JSON.parse(txt):{}}catch{j={raw:txt}}if(r.status===401||r.status===403){logout(false);throw new Error('Sessão expirada ou acesso não autorizado')}if(!r.ok)throw new Error(readableError(j,txt,r.status));return j}
async function safeCall(path,fallback){try{return await call(path)}catch(error){console.warn(path,error);return fallback}}

async function login(){try{const email=$('email').value.trim(),password=$('password').value;if(!email||!password)throw new Error('Informe e-mail e senha');$('status').textContent='Entrando...';const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const txt=await r.text();let j={};try{j=JSON.parse(txt)}catch{j={raw:txt}}const accessToken=j.accessToken||j.access_token||j.token||j.tokens?.accessToken;if(!r.ok||!accessToken)throw new Error(readableError(j,txt,r.status));setToken(accessToken);$('password').value='';await refresh()}catch(error){setToken('');data={};$('status').textContent='Erro: '+error.message;render();toast(error.message,true)}}
function logout(show=true){setToken('');data={};$('status').textContent='Sessão encerrada';render();if(show)toast('Sessão encerrada')}

async function refresh(){if(!token()){render();return}try{$('status').textContent='Carregando painel...';const [ops,users,treasury,clientsFull,dash,deposits,earlySummary,earlyLeads,crm,audit,checkout,trades]=await Promise.all([
  safeCall('/admin/ops-center',{}),safeCall('/admin/users',[]),safeCall('/treasury-admin/dashboard',{}),safeCall('/treasury-admin/clients-full',{}),safeCall('/admin/dashboard',{}),safeCall('/admin/deposits',[]),safeCall('/early-access/admin/summary',{total:0,qualified:0,byStatus:{}}),safeCall('/early-access/admin/leads?limit=500',{leads:[],total:0}),safeCall('/admin/crm',{contacts:[],summary:{}}),safeCall('/admin/audit?limit=200',{events:[]}),safeCall('/merchant-admin/transactions?limit=300',{transactions:[]}),safeCall('/treasury-admin/trades?limit=300',{trades:[]})
]);data={ops:ops||{},users:Array.isArray(users)?users:(users?.users||[]),treasury:treasury||{},clientsFull:clientsFull||{},dash:dash||{},deposits:Array.isArray(deposits)?deposits:(deposits?.deposits||[]),earlySummary:earlySummary||{},earlyLeads:earlyLeads||{leads:[]},crm:crm||{contacts:[]},audit:audit||{events:[]},checkout:checkout||{transactions:[]},trades:trades||{trades:[]},ledgerBalances:{}};await Promise.all(clients().map(async c=>{try{const b=await call('/ledger/balance?userId='+encodeURIComponent(c.id)+'&mode=real');data.ledgerBalances[c.id]=b.balances||{}}catch{data.ledgerBalances[c.id]={}}}));$('status').textContent='Painel carregado';$('lastUpdated').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR');render()}catch(error){$('status').textContent='Erro: '+error.message;render();toast(error.message,true)}}

function clients(){return data.clientsFull?.clients||data.users||[]}
function clientById(id){return clients().find(c=>c.id===id)||{}}
function ledgerUsdc(c){return Number(data.ledgerBalances?.[c.id]?.USDC??c.balances?.USDC??c.availableBalanceUsdc??0)}
function isRealClient(c){return c&&c.isClientLiability!==false&&!c.isTestOrAdmin&&c.isActive!==false&&!c.isBlocked&&!c.isArchived}
function officialClientUsdcLiability(){return clients().filter(isRealClient).reduce((sum,c)=>sum+ledgerUsdc(c),0)}
function treasuryUsdc(){return Number(data.treasury?.reserves?.treasuryUsdc||0)}
function officialReserveGap(){return treasuryUsdc()-officialClientUsdcLiability()}
function payments(){return data.dash?.latest?.payments||[]}
function checkoutRows(){return data.checkout?.transactions||[]}
function treasuryTrades(){return data.trades?.trades||[]}
function setTab(value){tab=value;document.querySelectorAll('nav button').forEach(button=>button.classList.toggle('active',button.dataset.tab===value));render()}
function card(label,value,cls=''){return '<div class="card"><div class="muted">'+esc(label)+'</div><div class="kpi '+cls+'">'+value+'</div></div>'}
function deadlineDate(v){const d=new Date(v||Date.now());d.setDate(d.getDate()+1);return d}

function render(){const titles={ops:'Visão Geral',primeiros:'Primeiros Nexa',clientes:'Clientes',checkout:'Checkout PJ',financeiro:'Resgates Pix',tesouraria:'Tesouraria',crm:'CRM',audit:'Auditoria',raw:'Debug'};$('title').textContent=titles[tab]||tab;if(!token()){$('content').innerHTML='<div class="card"><h3>Acesso restrito</h3><p class="muted">Faça login com a conta administrativa.</p></div>';return}if(tab==='ops')return renderOps();if(tab==='primeiros')return renderPrimeiros();if(tab==='clientes')return renderClientes();if(tab==='checkout')return renderCheckout();if(tab==='financeiro')return renderFinanceiro();if(tab==='tesouraria')return renderTesouraria();if(tab==='crm')return renderCrm();if(tab==='audit')return renderAudit();$('content').innerHTML='<pre>'+esc(JSON.stringify(data,null,2))+'</pre>'}

function renderOps(){const openPayments=payments().filter(p=>['pending','processing'].includes(String(p.status).toLowerCase()));const pendingCheckout=checkoutRows().filter(t=>!t.settled&&!['failed','cancelled'].includes(String(t.status).toLowerCase()));const early=data.earlySummary||{};const gap=officialReserveGap();$('content').innerHTML='<div class="grid">'+card('Primeiros Nexa',n(early.total||0,0))+card('Leads qualificados',n(early.qualified||0,0),'ok')+card('Checkout PJ pendente',pendingCheckout.length,pendingCheckout.length?'warn':'ok')+card('Resgates aguardando',openPayments.length,openPayments.length?'warn':'ok')+'</div><div class="grid">'+card('Clientes',clients().length)+card('USDC clientes',n(officialClientUsdcLiability(),8))+card('Tesouraria USDC',n(treasuryUsdc(),8))+card('Gap de reserva',n(gap,8),gap>=0?'ok':'bad')+'</div><div class="card notice"><h3>Separação operacional</h3><p><b>Lead</b> é contato de aquisição. <b>Cliente</b> é conta criada. <b>Saldo</b> só existe no ledger ou na blockchain. <b>Liquidação</b> exige valores e referências reais.</p></div>'}

const leadLabels={new:'Novo',qualified:'Qualificado',invited:'Convidado',activated:'Ativado',paused:'Pausado',unsubscribed:'Descadastrado'};
function leadClass(status){return status==='activated'?'green':status==='paused'||status==='unsubscribed'?'gray':status==='qualified'||status==='invited'?'blue':'yellow'}
function filteredLeads(){const q=leadFilter.trim().toLowerCase();return (data.earlyLeads?.leads||[]).filter(lead=>(leadStatus==='all'||lead.status===leadStatus)&&(!q||[lead.fullName,lead.email,lead.phone,lead.primaryInterest,lead.source].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderPrimeiros(){const summary=data.earlySummary||{byStatus:{}};const rows=filteredLeads();$('content').innerHTML='<div class="grid">'+card('Total',summary.total||0)+card('Novos',summary.byStatus?.new||0,'warn')+card('Qualificados',summary.byStatus?.qualified||0,'ok')+card('Ativados',summary.byStatus?.activated||0,'ok')+'</div><div class="toolbar"><input id="leadSearch" placeholder="Buscar nome, e-mail, telefone ou origem" value="'+esc(leadFilter)+'"><select id="leadStatus"><option value="all">Todos os status</option>'+Object.entries(leadLabels).map(([value,label])=>'<option value="'+value+'" '+(leadStatus===value?'selected':'')+'>'+label+'</option>').join('')+'</select><button onclick="exportLeadsCsv()">Exportar CSV</button></div><div class="card notice"><b>Métrica principal:</b> pessoas qualificadas na lista. Um lead não vira cliente financeiro sem convite, cadastro, KYC e aceite próprios.</div><div class="card scroll"><table><thead><tr><th>Pessoa</th><th>Perfil</th><th>Origem</th><th>Status</th><th>Ações</th></tr></thead><tbody>'+rows.map(lead=>'<tr><td><b>'+esc(lead.fullName)+'</b><br><span class="muted">'+esc(lead.email)+' · '+esc(lead.phone||'sem WhatsApp')+'</span></td><td>'+esc(lead.cryptoExperience||'não informado')+'<br><span class="muted">'+esc(lead.primaryInterest||'interesse não informado')+'</span></td><td>'+esc(lead.source||'direto')+'<br><span class="muted">'+fmtDate(lead.createdAt)+'</span></td><td>'+pill(leadLabels[lead.status]||lead.status,leadClass(lead.status))+'</td><td><div class="row-actions"><button class="small-btn" onclick="openLead(\''+lead.id+'\')">Detalhes</button><button class="small-btn green" onclick="setLeadStatus(\''+lead.id+'\',\'qualified\')">Qualificar</button><button class="small-btn" onclick="setLeadStatus(\''+lead.id+'\',\'invited\')">Convidar</button></div></td></tr>').join('')+'</tbody></table></div>';const search=$('leadSearch'),status=$('leadStatus');if(search)search.oninput=e=>{leadFilter=e.target.value;renderPrimeiros()};if(status)status.onchange=e=>{leadStatus=e.target.value;renderPrimeiros()}}
function leadById(id){return (data.earlyLeads?.leads||[]).find(lead=>lead.id===id)}
function openLead(id){const lead=leadById(id);if(!lead)return;openModal('<h2 id="modalTitle">'+esc(lead.fullName)+'</h2><div class="modal-section"><p><b>E-mail:</b> '+esc(lead.email)+'<br><b>WhatsApp:</b> '+esc(lead.phone||'—')+'<br><b>Canal:</b> '+esc(lead.preferredChannel||'—')+'<br><b>Experiência:</b> '+esc(lead.cryptoExperience||'—')+'<br><b>Interesse:</b> '+esc(lead.primaryInterest||'—')+'<br><b>Origem:</b> '+esc(lead.source||'—')+' / '+esc(lead.campaign||'—')+'<br><b>Indicação:</b> '+esc(lead.referredByCode||'—')+'</p></div><div class="modal-section"><label class="muted">Status</label><select id="leadModalStatus">'+Object.entries(leadLabels).map(([value,label])=>'<option value="'+value+'" '+(lead.status===value?'selected':'')+'>'+label+'</option>').join('')+'</select><label class="muted">Observações administrativas</label><textarea id="leadModalNotes">'+esc(lead.adminNotes||'')+'</textarea><button class="green" onclick="saveLead(\''+id+'\')">Salvar</button></div>')}
async function saveLead(id){try{await call('/early-access/admin/leads/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({status:$('leadModalStatus').value,adminNotes:$('leadModalNotes').value})});closeModal();toast('Lead atualizado');await refresh()}catch(error){toast(error.message,true)}}
async function setLeadStatus(id,status){try{await call('/early-access/admin/leads/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({status})});toast('Status atualizado');await refresh()}catch(error){toast(error.message,true)}}
function exportLeadsCsv(){const leads=filteredLeads();const columns=['fullName','email','phone','preferredChannel','cryptoExperience','primaryInterest','source','campaign','status','createdAt'];const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv='\ufeff'+columns.join(';')+'\n'+leads.map(lead=>columns.map(key=>quote(lead[key])).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='primeiros-nexa-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(url)}

function renderClientes(){const rows=clients();$('content').innerHTML='<div class="grid">'+card('Total',rows.length)+card('KYC aprovado',rows.filter(x=>x.kycStatus==='approved').length,'ok')+card('Com saldo',rows.filter(x=>ledgerUsdc(x)>0).length)+card('Bloqueados/arquivados',rows.filter(x=>x.isBlocked||x.isArchived||x.isActive===false).length,'warn')+'</div><div class="card notice"><b>Saldo oficial:</b> Ledger real. Bloquear acesso ou arquivar conta não apaga histórico nem altera saldo.</div><div class="card scroll"><table><thead><tr><th>Nome</th><th>Contato</th><th>Status</th><th>Saldo oficial</th><th>Ações</th></tr></thead><tbody>'+rows.map(user=>'<tr><td><b>'+esc(user.fullName||'—')+'</b><br><span class="muted">'+esc(user.cpfCnpj||user.cpf||'—')+' @'+esc(user.username||'—')+'</span></td><td>'+esc(user.email||'—')+'<br>'+esc(user.phone||'—')+'</td><td>'+pill(user.kycStatus,user.kycStatus==='approved'?'green':'yellow')+' '+(user.isBlocked?pill('bloqueado','red'):'')+' '+(user.isArchived?pill('arquivado','gray'):'')+'</td><td><b>'+n(ledgerUsdc(user),8)+' USDC</b><br><span class="muted">'+brl(data.ledgerBalances?.[user.id]?.BRL||0)+'</span></td><td><div class="row-actions"><button class="small-btn" onclick="report(\''+user.id+'\')">Extrato</button><button class="small-btn green" onclick="openClientCrm(\''+user.id+'\')">CRM</button><button class="small-btn yellow" onclick="toggleBlock(\''+user.id+'\','+(!user.isBlocked)+')">'+(user.isBlocked?'Desbloquear':'Bloquear')+'</button><button class="small-btn ghost" onclick="toggleArchive(\''+user.id+'\','+(!user.isArchived)+')">'+(user.isArchived?'Restaurar':'Arquivar')+'</button></div></td></tr>').join('')+'</tbody></table></div>'}
async function toggleBlock(id,blocked){const reason=prompt(blocked?'Motivo do bloqueio:':'Motivo do desbloqueio:','Ação administrativa com preservação integral do histórico')||'';if(!reason.trim())return;try{await call('/admin/users/'+encodeURIComponent(id)+'/block',{method:'POST',body:JSON.stringify({blocked,reason})});toast(blocked?'Cliente bloqueado':'Cliente desbloqueado');await refresh()}catch(error){toast(error.message,true)}}
async function toggleArchive(id,archived){const reason=prompt(archived?'Motivo do arquivamento:':'Motivo da restauração:','Histórico preservado')||'';if(!reason.trim())return;try{await call('/admin/users/'+encodeURIComponent(id)+'/archive',{method:'POST',body:JSON.stringify({archived,reason})});toast(archived?'Cliente arquivado':'Cliente restaurado');await refresh()}catch(error){toast(error.message,true)}}
async function report(id){try{const client=clientById(id);const result=await call('/ledger/statement?userId='+encodeURIComponent(id)+'&limit=100&mode=real');const rows=(result.statement||[]).map(entry=>{const signal=entry.direction==='credit'?'+':'-';return fmtDate(entry.createdAt)+' | '+signal+n(entry.amount,8)+' '+entry.asset+' | '+(entry.display?.title||entry.type)+' | '+(entry.description||'')});openModal('<h2 id="modalTitle">Extrato de '+esc(client.fullName||'Cliente')+'</h2><p><b>Saldo atual:</b> '+n(ledgerUsdc(client),8)+' USDC</p><pre>'+esc(rows.join('\n')||'Nenhum lançamento encontrado.')+'</pre>')}catch(error){toast(error.message,true)}}

const checkoutLabels={awaiting_pix:'Aguardando Pix',pix_confirmed_fee_pending:'Conferir tarifa Pix',awaiting_usdc_purchase:'Comprar USDC',awaiting_usdc_payout:'Enviar USDC',awaiting_brl_payout:'Enviar Pix ao lojista',completed:'Concluído',failed:'Falhou',cancelled:'Cancelado'};
function renderCheckout(){const rows=checkoutRows();const pending=rows.filter(row=>!row.settled&&!['failed','cancelled'].includes(row.status));const netRevenue=rows.reduce((sum,row)=>sum+Number(row.nexaNetRevenueBrl||0),0);$('content').innerHTML='<div class="grid">'+card('Cobranças',rows.length)+card('Pendentes',pending.length,pending.length?'warn':'ok')+card('Concluídas',rows.filter(row=>row.settled).length,'ok')+card('Receita Nexa conciliada',brl(netRevenue))+'</div><div class="card notice"><b>Ordem obrigatória:</b> confirmar Pix e tarifa real → registrar compra real de USDC ou preparar Pix → confirmar pagamento final. O painel não aceita conclusão por estimativa.</div><div class="card scroll"><table><thead><tr><th>Cobrança</th><th>Valores</th><th>Status</th><th>Referências</th><th>Ação segura</th></tr></thead><tbody>'+rows.map(row=>'<tr><td><b>'+brl(row.amountBrl)+'</b><br><span class="muted">'+esc(row.description||row.id)+'<br>'+fmtDate(row.createdAt)+'</span></td><td>Taxa Nexa: '+brl(row.serviceFeeBrl)+'<br>Pix In: '+brl(row.pixInFeeBrl)+'<br>Lojista: '+(row.settlementCurrency==='USDC'?n(row.merchantPayoutUsdc??row.amountUsdc,8)+' USDC':brl(row.merchantPayoutBrl||0))+'</td><td>'+pill(checkoutLabels[row.status]||row.status,statusClass(row.status))+'<br><span class="muted">'+esc(row.settlementCurrency)+'</span></td><td><span class="muted">Pix:</span> '+esc(row.providerReference||row.pixTransactionId||'—')+'<br><span class="muted">Liquidação:</span> '+esc(row.payoutReference||row.settlementReference||'—')+'</td><td>'+checkoutAction(row)+'</td></tr>').join('')+'</tbody></table></div>'}
function checkoutAction(row){if(row.status==='awaiting_pix'||row.status==='pix_confirmed_fee_pending')return '<button class="small-btn green" onclick="confirmMerchantPix(\''+row.id+'\','+Number(row.amountBrl)+')">Confirmar Pix real</button>';if(row.status==='awaiting_usdc_purchase')return '<button class="small-btn" onclick="recordMerchantPurchase(\''+row.id+'\','+Number(row.brlPurchaseBudget||0)+')">Registrar compra USDC</button>';if(row.status==='awaiting_usdc_payout')return '<button class="small-btn green" onclick="confirmMerchantUsdc(\''+row.id+'\','+Number(row.merchantPayoutUsdc||0)+')">Confirmar envio USDC</button>';if(row.status==='awaiting_brl_payout')return '<button class="small-btn green" onclick="confirmMerchantBrl(\''+row.id+'\','+Number(row.merchantPayoutBrl||0)+','+Number(row.pixOutFeeBrl||1)+')">Confirmar Pix lojista</button>';return '<span class="muted">Sem ação pendente</span>'}
async function confirmMerchantPix(id,gross){const fee=parseMoney(prompt('Tarifa Pix In REAL cobrada pelo provedor:','5,00'));const ref=prompt('Referência real do Pix recebido:','')||'';if(!Number.isFinite(fee)||fee<0||ref.trim().length<4)return toast('Tarifa e referência são obrigatórias',true);try{await call('/merchant-admin/transactions/'+id+'/confirm-pix',{method:'POST',body:JSON.stringify({grossBrl:gross,actualPixInFeeBrl:fee,providerReference:ref.trim()})});toast('Pix conciliado');await refresh()}catch(error){toast(error.message,true)}}
async function recordMerchantPurchase(id,budget){const brlDebited=parseMoney(prompt('BRL total debitado na compra real:',String(budget).replace('.',',')));const usdcReceived=Number(String(prompt('USDC líquido realmente recebido:','')||'').replace(',','.'));const ref=prompt('Referência da compra no provedor:','')||'';const txHash=prompt('Hash real da transação:','0x')||'';if(!Number.isFinite(brlDebited)||brlDebited<=0||!Number.isFinite(usdcReceived)||usdcReceived<=0)return toast('Valores reais são obrigatórios',true);try{await call('/merchant-admin/transactions/'+id+'/record-usdc-purchase',{method:'POST',body:JSON.stringify({brlDebitedTotal:brlDebited,usdcReceivedNet:usdcReceived,providerReference:ref.trim(),provider:'manual_treasury',transactionHash:txHash.trim()})});toast('Compra de USDC registrada');await refresh()}catch(error){toast(error.message,true)}}
async function confirmMerchantUsdc(id,expected){const actual=Number(String(prompt('USDC efetivamente enviado:',String(expected))||'').replace(',','.'));const ref=prompt('Referência do envio:','')||'';const txHash=prompt('Hash real do envio on-chain:','0x')||'';if(!Number.isFinite(actual)||actual<=0)return toast('Valor enviado é obrigatório',true);if(!confirm('Confirma que o USDC foi REALMENTE enviado para a wallet validada?'))return;try{await call('/merchant-admin/transactions/'+id+'/confirm-usdc-payout',{method:'POST',body:JSON.stringify({payoutReference:ref.trim(),transactionHash:txHash.trim(),actualUsdcSent:actual})});toast('Liquidação USDC concluída');await refresh()}catch(error){toast(error.message,true)}}
async function confirmMerchantBrl(id,expected,fee){const payout=parseMoney(prompt('Pix REAL enviado ao lojista:',String(expected).replace('.',',')));const pixFee=parseMoney(prompt('Custo Pix Out REAL:',String(fee).replace('.',',')));const ref=prompt('Referência real do Pix enviado:','')||'';if(!confirm('Confirma que o Pix foi REALMENTE enviado ao lojista?'))return;try{await call('/merchant-admin/transactions/'+id+'/confirm-brl-payout',{method:'POST',body:JSON.stringify({payoutReference:ref.trim(),actualPayoutBrl:payout,actualPixOutFeeBrl:pixFee})});toast('Liquidação BRL concluída');await refresh()}catch(error){toast(error.message,true)}}

function tradeForPayment(paymentId){return treasuryTrades().find(trade=>trade.orderId===paymentId&&trade.side==='sell_usdc')}
function renderFinanceiro(){const rows=payments().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const open=rows.filter(p=>['pending','processing'].includes(String(p.status).toLowerCase()));const total=open.reduce((sum,p)=>sum+Number(p.amountBrl||0),0);$('content').innerHTML='<div class="grid">'+card('Resgates aguardando',open.length,open.length?'warn':'ok')+card('Valor solicitado',brl(total))+card('Com venda registrada',open.filter(p=>tradeForPayment(p.id)).length)+card('Prazo vencido',open.filter(p=>deadlineDate(p.createdAt)<new Date()).length,'warn')+'</div><div class="card critical"><b>Nunca confirme o Pix direto.</b> Primeiro registre a venda real de USDC. Depois de receber BRL e enviar o Pix, concilie o pagamento usando a referência real.</div><div class="grid2">'+(open.map(payment=>{const client=clientById(payment.userId),trade=tradeForPayment(payment.id);return '<div class="card '+(deadlineDate(payment.createdAt)<new Date()?'critical':'')+'"><div class="eyebrow">RESGATE #'+esc(payment.id.slice(0,8))+'</div><h2>'+brl(payment.amountBrl)+'</h2><p><b>Cliente:</b> '+esc(client.fullName||payment.userId)+'<br><b>Chave Pix:</b> '+esc(payment.pixKey||'—')+'<br><b>USDC reservado:</b> '+n(payment.amountUsdc,8)+'<br><b>Solicitado:</b> '+fmtDate(payment.createdAt)+'</p>'+(trade?'<div class="rule-box"><b>Venda registrada:</b> '+n(trade.usdcAmount,8)+' USDC → '+brl(trade.brlAmount)+'<br>Status: '+esc(trade.status)+'<br>Máximo ao cliente: '+brl(trade.maximumCustomerPayoutBrl)+'</div><div class="actions"><button class="green" onclick="settleRedemption(\''+payment.id+'\',\''+trade.id+'\','+Number(trade.customerPayoutBrl||payment.amountBrl)+','+Number(trade.pixOutFeeBrl||1)+')">Conciliar Pix enviado</button></div>':'<button onclick="recordRedemptionSale(\''+payment.id+'\','+Number(payment.amountUsdc||0)+','+Number(payment.amountBrl||0)+')">Registrar venda real de USDC</button>')+'</div>'}).join('')||'<div class="card goodbox"><h3>Nenhum resgate aguardando.</h3></div>')+'</div>'}
async function recordRedemptionSale(paymentId,usdc,payout){const brlNet=parseMoney(prompt('BRL líquido REAL recebido na venda:',''));const pixFee=parseMoney(prompt('Custo Pix Out esperado:','1,00'));const ref=prompt('Referência única da venda no provedor:','metamask-sell-'+Date.now())||'';const txHash=prompt('Hash ou referência real da venda:','')||'';if(!Number.isFinite(brlNet)||brlNet<=0)return toast('Informe o BRL realmente recebido',true);try{await call('/treasury-admin/trades/sell-usdc',{method:'POST',body:JSON.stringify({externalReference:ref.trim(),usdcDebitedTotal:usdc,brlReceivedNet:brlNet,plan:'FREE',customerPayoutBrl:payout,pixOutFeeBrl:pixFee,provider:'manual_treasury',transactionHash:txHash.trim(),orderId:paymentId,note:'Venda real para resgate de cliente'})});toast('Venda real registrada; agora faça o Pix dentro do limite calculado');await refresh()}catch(error){toast(error.message,true)}}
async function settleRedemption(paymentId,tradeId,payout,pixFee){const actual=parseMoney(prompt('Valor REAL do Pix enviado ao cliente:',String(payout).replace('.',',')));const fee=parseMoney(prompt('Custo Pix Out REAL:',String(pixFee).replace('.',',')));const ref=prompt('Referência real do Pix enviado:','')||'';if(!confirm('Confirma que o Pix foi REALMENTE enviado e está visível no provedor?'))return;try{await call('/treasury-admin/trades/'+tradeId+'/settle-payout',{method:'POST',body:JSON.stringify({payoutReference:ref.trim(),actualCustomerPayoutBrl:actual,actualPixOutFeeBrl:fee,note:'Pix enviado e conciliado no Control Center'})});await call('/payment/confirm',{method:'POST',body:JSON.stringify({paymentId,status:'completed',reason:'Venda real e Pix conciliados; trade '+tradeId+'; referência '+ref.trim()})});toast('Resgate liquidado e pedido encerrado');await refresh()}catch(error){toast(error.message,true)}}

function renderTesouraria(){const liability=officialClientUsdcLiability(),treasury=treasuryUsdc(),gap=officialReserveGap(),accounts=data.treasury?.segregatedAccounts?.byType||{};$('content').innerHTML='<div class="grid">'+card('Tesouraria USDC',n(treasury,8),'ok')+card('Passivo clientes',n(liability,8))+card('Gap',n(gap,8),gap>=0?'ok':'bad')+card('Receita BRL',brl(accounts.revenue?.BRL||0))+'</div><div class="card"><h3>Contas segregadas</h3><pre>'+esc(JSON.stringify(accounts,null,2))+'</pre></div><div class="card notice"><b>Regra:</b> receita, reserva e caixa operacional não são o mesmo saldo. Compra e venda real devem ser registradas pelo endpoint de tesouraria.</div>'}

const crmStageLabels={new:'Novo',contacted:'Contatado',qualified:'Qualificado',onboarding:'Onboarding',active:'Ativo',blocked:'Bloqueado',archived:'Arquivado'};
function renderCrm(){const contacts=data.crm?.contacts||[];const grouped={};contacts.forEach(item=>{const stage=item.crm?.stage||'new';(grouped[stage]||=[]).push(item)});$('content').innerHTML='<div class="grid">'+card('Contatos CRM',contacts.length)+card('Follow-ups vencidos',data.crm?.summary?.overdue||0,'warn')+card('Ativos',data.crm?.summary?.active||0,'ok')+card('Onboarding',data.crm?.summary?.onboarding||0)+'</div><div class="pipeline">'+Object.keys(crmStageLabels).map(stage=>'<div class="pipeline-column"><div class="pipeline-head"><h3>'+crmStageLabels[stage]+'</h3>'+pill((grouped[stage]||[]).length,'gray')+'</div>'+(grouped[stage]||[]).map(item=>'<div class="crm-card '+(item.crm?.nextFollowUpAt&&new Date(item.crm.nextFollowUpAt)<new Date()?'overdue':'')+'"><h4>'+esc(item.user?.fullName||item.user?.email)+'</h4><p>'+esc(item.user?.email||'')+'<br>Próximo contato: '+fmtDate(item.crm?.nextFollowUpAt)+'</p><div class="tag-list">'+(item.crm?.tags||[]).map(tag=>'<span class="tag">'+esc(tag)+'</span>').join('')+'</div><button class="small-btn" onclick="openCrm(\''+item.user.id+'\')">Abrir</button></div>').join('')+'</div>').join('')+'</div>'}
async function openCrm(userId){try{const detail=await call('/admin/crm/'+encodeURIComponent(userId));const crm=detail.crm||{},user=detail.user||{};openModal('<h2 id="modalTitle">CRM · '+esc(user.fullName||user.email)+'</h2><div class="form-grid"><div class="form-field"><label>Etapa</label><select id="crmStage">'+Object.entries(crmStageLabels).map(([value,label])=>'<option value="'+value+'" '+(crm.stage===value?'selected':'')+'>'+label+'</option>').join('')+'</select></div><div class="form-field"><label>Próximo contato</label><input id="crmNext" type="datetime-local" value="'+(crm.nextFollowUpAt?new Date(crm.nextFollowUpAt).toISOString().slice(0,16):'')+'"></div><div class="form-field full"><label>Tags separadas por vírgula</label><input id="crmTags" value="'+esc((crm.tags||[]).join(', '))+'"></div><div class="form-field full"><label>Resumo</label><textarea id="crmSummary">'+esc(crm.summary||'')+'</textarea></div></div><button class="green" onclick="saveCrm(\''+userId+'\')">Salvar CRM</button><div class="modal-section"><h3>Nova nota</h3><textarea id="crmNote" placeholder="Registre contato, dúvida, objeção ou próximo passo"></textarea><button onclick="addCrmNote(\''+userId+'\')">Adicionar nota</button></div><div class="modal-section"><h3>Histórico</h3>'+(detail.notes||[]).map(note=>'<div class="note"><small>'+fmtDate(note.createdAt)+' · '+esc(note.channel)+'</small>'+esc(note.body)+'</div>').join('')+'</div>')}catch(error){toast(error.message,true)}}
async function saveCrm(userId){try{await call('/admin/crm/'+encodeURIComponent(userId),{method:'PUT',body:JSON.stringify({stage:$('crmStage').value,tags:$('crmTags').value.split(',').map(v=>v.trim()).filter(Boolean),summary:$('crmSummary').value,nextFollowUpAt:$('crmNext').value?new Date($('crmNext').value).toISOString():null})});closeModal();toast('CRM atualizado');await refresh()}catch(error){toast(error.message,true)}}
async function addCrmNote(userId){const body=$('crmNote').value.trim();if(body.length<2)return toast('Escreva a nota',true);try{await call('/admin/crm/'+encodeURIComponent(userId)+'/notes',{method:'POST',body:JSON.stringify({body,channel:'internal'})});toast('Nota adicionada');await openCrm(userId);await refresh()}catch(error){toast(error.message,true)}}
function openClientCrm(id){setTab('crm');setTimeout(()=>openCrm(id),0)}

function renderAudit(){const events=data.audit?.events||data.audit?.audit||[];$('content').innerHTML='<div class="card"><h3>Trilha administrativa</h3><p class="muted">Bloqueios, arquivamentos, CRM e ações sensíveis permanecem registrados.</p>'+(events.length?events.map(event=>'<div class="audit-row"><small>'+fmtDate(event.createdAt)+'</small><b>'+esc(event.action)+'</b><div>'+esc(event.reason||'—')+'<br><small>'+esc(event.adminEmail||'')+' · '+esc(event.targetUserId||'')+'</small></div></div>').join(''):'<div class="empty">Nenhum evento carregado.</div>')+'</div>'}

document.addEventListener('DOMContentLoaded',()=>{setToken('');document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>setTab(button.dataset.tab));document.querySelectorAll('[data-close-modal]').forEach(node=>node.onclick=closeModal);$('loginBtn').onclick=login;$('logoutBtn').onclick=()=>logout(true);$('refreshBtn').onclick=refresh;$('password').onkeydown=event=>{if(event.key==='Enter')login()};setTab('ops');render()});
